version: "3"
services:
  web:
    container_name: web
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
volumes:
  db-data:
    driver: local
