version: "3"
services:
  web:
    container_name: web
    build: ./client
    restart: always
    # command: ["npm", "run", "serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./myshare:/shared"

  api:
    container_name: api
    build: .
    restart: always
    command: Backend/setup.sh
    ports:
      - "3000:3000"
    depends_on:
      - "web"
      - "mongo"
    links:
      - mongo
      - hub
      - chrome
    volumes:
      - "./myshare:/shared"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
  hub:
    container_name: hub
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
  chrome:
    image: selenium/node-chrome-debug
    container_name: chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
      - "./storage/browser/profiles:/home/twai/profiles"
      # - "~/Library/Application Support/Google/Chrome:/home/seluser/profiles"
    ports:
      - "9001:5900"
    links:
      - hub

volumes:
  db-data:
    driver: local
  myshare:
    driver: local
